use std::{
    fs,
    io::{self, IsTerminal, Read, Write},
    net::{TcpStream, ToSocketAddrs},
    path::Path,
    time::Duration,
};

use anyhow::{Context, Result, bail};
use clap::{Parser, ValueEnum};
use crossterm::{
    cursor,
    event::{self, Event, KeyCode},
    execute,
    terminal::{self, ClearType},
};
use scraper::{ElementRef, Html, Selector, node::Node};
use url::Url;

const DEFAULT_MAX_BYTES: usize = 8 * 1024 * 1024;
const ESC: char = '\u{1b}';

#[derive(Debug, Parser)]
#[command(
    name = "sl",
    version,
    about = "A safe, read-only terminal document reader"
)]
pub struct Cli {
    /// Files to read, or one literal local http:// URL. Use - for standard input.
    #[arg(value_name = "FILE|URL", default_value = "-")]
    pub files: Vec<String>,

    /// Force the input type instead of detecting it.
    #[arg(short = 't', long = "type", value_enum)]
    pub kind: Option<DocumentKind>,

    /// Emit unstyled text and do not open a pager.
    #[arg(long)]
    pub plain: bool,

    /// Control ANSI colour output. Input escape sequences are never emitted.
    #[arg(long, value_enum, default_value_t = ColorMode::Auto)]
    pub color: ColorMode,

    /// Select an output theme. `mono` never emits ANSI styling.
    #[arg(long, value_enum, default_value_t = Theme::Default)]
    pub theme: Theme,

    /// Render as though the terminal has this many columns.
    #[arg(long, value_name = "COLUMNS")]
    pub width: Option<usize>,

    /// Maximum bytes read per input.
    #[arg(long, default_value_t = DEFAULT_MAX_BYTES, value_name = "BYTES")]
    pub max_bytes: usize,

    /// Print output directly rather than using the built-in pager.
    #[arg(long)]
    pub no_pager: bool,

    /// Omit text line numbers.
    #[arg(long)]
    pub no_line_numbers: bool,

    /// List supported document types.
    #[arg(long)]
    pub list_types: bool,

    /// Suppress non-fatal warnings.
    #[arg(short, long)]
    pub quiet: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum ColorMode {
    Auto,
    Always,
    Never,
}

/// Terminal styling palette. Themes only control ANSI generated by `sl`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum Theme {
    Default,
    Dark,
    Mono,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum DocumentKind {
    Text,
    Markdown,
    Json,
    Yaml,
    Toml,
    Csv,
    Tsv,
    Code,
    Binary,
}

impl DocumentKind {
    fn detect(name: Option<&str>, bytes: &[u8]) -> Self {
        let lower = name.unwrap_or_default().to_ascii_lowercase();
        let file = Path::new(&lower)
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or_default();
        // Basenames have no useful extension, so keep this audit explicit. Structured
        // extensions below deliberately retain priority for files such as Cargo.toml.
        if matches!(
            file,
            "makefile"
                | "gnumakefile"
                | "dockerfile"
                | "containerfile"
                | "cmakelists.txt"
                | "rakefile"
                | "gemfile"
                | "procfile"
                | ".gitignore"
                | ".gitattributes"
                | ".gitmodules"
                | ".editorconfig"
                | ".dockerignore"
                | ".npmrc"
                | ".envrc"
        ) {
            return Self::Code;
        }
        let extension = file.rsplit_once('.').map(|(_, extension)| extension);
        match extension {
            Some("md" | "markdown" | "mdown") => Self::Markdown,
            Some("json" | "jsonc" | "ndjson") => Self::Json,
            Some("yaml" | "yml") => Self::Yaml,
            Some("toml") => Self::Toml,
            Some("csv") => Self::Csv,
            Some("tsv") => Self::Tsv,
            Some(
                "rs" | "py" | "pyw" | "pyi" | "js" | "mjs" | "cjs" | "jsx" | "ts" | "mts" | "cts"
                | "tsx" | "sh" | "bash" | "zsh" | "fish" | "ksh" | "go" | "c" | "h" | "cc" | "cpp"
                | "cxx" | "hpp" | "java" | "rb" | "php" | "swift" | "kt" | "sql" | "html" | "css"
                | "xml" | "ini" | "cfg" | "conf" | "properties" | "env",
            ) => Self::Code,
            _ if bytes.contains(&0) || std::str::from_utf8(bytes).is_err() => Self::Binary,
            _ if looks_like_json(bytes) => Self::Json,
            _ if looks_like_markdown(bytes) => Self::Markdown,
            _ => Self::Text,
        }
    }
}

#[derive(Clone, Copy)]
struct RenderOptions {
    color: bool,
    theme: Theme,
    width: usize,
    line_numbers: bool,
}

#[derive(Clone, Copy)]
enum SourceLanguage {
    Rust,
    Python,
    JavaScript,
    Shell,
    Go,
    Generic,
}

impl SourceLanguage {
    fn from_name(name: &str) -> Option<Self> {
        let extension = Path::new(name)
            .extension()
            .and_then(|value| value.to_str())?
            .to_ascii_lowercase();
        Some(match extension.as_str() {
            "rs" => Self::Rust,
            "py" | "pyw" | "pyi" => Self::Python,
            "js" | "mjs" | "cjs" | "jsx" | "ts" | "mts" | "cts" | "tsx" => Self::JavaScript,
            "sh" | "bash" | "zsh" | "fish" | "ksh" => Self::Shell,
            "go" => Self::Go,
            _ => Self::Generic,
        })
    }
}

pub fn run(cli: Cli) -> i32 {
    if cli.list_types {
        println!("text\nmarkdown\njson\nyaml\ntoml\ncsv\ntsv\ncode\nbinary");
        return 0;
    }
    if cli.max_bytes == 0 {
        eprintln!("sl: --max-bytes must be greater than zero");
        return 1;
    }

    let stdout_is_tty = io::stdout().is_terminal();
    let url_sources = cli
        .files
        .iter()
        .filter(|source| is_url_source(source))
        .count();
    if url_sources > 0 {
        if url_sources != cli.files.len() || url_sources != 1 {
            eprintln!("sl: URL mode accepts exactly one URL and cannot be mixed with files");
            return 1;
        }
        return run_web(&cli, stdout_is_tty);
    }
    let color = !cli.plain
        && cli.theme != Theme::Mono
        && match cli.color {
            ColorMode::Always => true,
            ColorMode::Never => false,
            ColorMode::Auto => stdout_is_tty && std::env::var_os("NO_COLOR").is_none(),
        };
    let options = RenderOptions {
        color,
        theme: cli.theme,
        width: cli.width.unwrap_or(100).max(20),
        line_numbers: !cli.no_line_numbers,
    };

    let mut documents = Vec::new();
    let mut failures = 0;
    for file in &cli.files {
        match read_and_render(file, cli.kind, cli.max_bytes, options) {
            Ok((rendered, warning)) => {
                if let Some(warning) = warning.filter(|_| !cli.quiet) {
                    eprintln!("sl: {file}: {warning}");
                }
                documents.push((file, rendered));
            }
            Err(error) => {
                eprintln!("sl: {file}: {error:#}");
                failures += 1;
            }
        }
    }
    if documents.is_empty() {
        return 1;
    }

    let multiple = documents.len() > 1;
    let mut output = String::new();
    for (index, (name, document)) in documents.iter().enumerate() {
        if multiple {
            if index > 0 {
                output.push('\n');
            }
            output.push_str(&format!(
                "{}\n",
                style(
                    &format!("==> {name} <=="),
                    theme_code("1;36", options.theme),
                    options.color,
                )
            ));
        }
        output.push_str(document);
        if !document.ends_with('\n') {
            output.push('\n');
        }
    }

    if stdout_is_tty && !cli.plain && !cli.no_pager {
        if let Err(error) = page(&output) {
            eprintln!("sl: pager error: {error:#}");
            return 1;
        }
    } else if let Err(error) = write_stdout(&output)
        && error.kind() != io::ErrorKind::BrokenPipe
    {
        eprintln!("sl: write error: {error}");
        return 1;
    }
    if failures > 0 { 2 } else { 0 }
}

fn is_url_source(source: &str) -> bool {
    source.starts_with("http://") || source.starts_with("https://")
}

#[derive(Clone)]
struct WebPage {
    url: Url,
    text: String,
    links: Vec<Url>,
}

fn validate_local_url(url: &Url) -> Result<()> {
    if url.scheme() != "http" {
        bail!("only http:// local URLs are permitted")
    }
    if !url.username().is_empty() || url.password().is_some() {
        bail!("URL credentials are not permitted")
    }
    let host = url.host_str().unwrap_or_default();
    let loopback_v4 = host.split('.').next() == Some("127")
        && host.split('.').count() == 4
        && host.split('.').all(|part| part.parse::<u8>().is_ok());
    if host != "localhost" && host != "::1" && host != "[::1]" && !loopback_v4 {
        bail!("URL host is not localhost or loopback")
    }
    Ok(())
}

fn fetch_web(start: &Url, max_bytes: usize) -> Result<WebPage> {
    let mut url = start.clone();
    for _ in 0..10 {
        validate_local_url(&url)?;
        let host = url.host_str().context("URL has no host")?;
        let address = if host == "[::1]" {
            format!("{host}:{}", url.port_or_known_default().unwrap_or(80))
        } else if host == "::1" {
            format!("[::1]:{}", url.port_or_known_default().unwrap_or(80))
        } else {
            format!("{host}:{}", url.port_or_known_default().unwrap_or(80))
        };
        let mut stream = address
            .to_socket_addrs()
            .with_context(|| "could not resolve local web server")?
            .filter(|candidate| candidate.ip().is_loopback())
            .find_map(|socket| TcpStream::connect_timeout(&socket, Duration::from_secs(3)).ok())
            .context("could not connect to a loopback local web server")?;
        stream.set_read_timeout(Some(Duration::from_secs(10)))?;
        stream.set_write_timeout(Some(Duration::from_secs(10)))?;
        let path = if url.path().is_empty() {
            "/"
        } else {
            url.path()
        };
        let target = match url.query() {
            Some(q) => format!("{path}?{q}"),
            None => path.to_owned(),
        };
        // Deliberately no proxy, cookies, auth, body, or non-GET request capability.
        write!(
            stream,
            "GET {target} HTTP/1.1\r\nHost: {host}\r\nConnection: close\r\nAccept: text/html, text/plain\r\n\r\n"
        )?;
        let response_limit = max_bytes.saturating_add(64 * 1024).saturating_add(1);
        let mut response = Vec::with_capacity(response_limit.min(64 * 1024));
        Read::by_ref(&mut stream)
            .take(response_limit as u64)
            .read_to_end(&mut response)?;
        if response.len() == response_limit {
            bail!("response exceeds --max-bytes")
        }
        let split = response
            .windows(4)
            .position(|w| w == b"\r\n\r\n")
            .context("invalid HTTP response")?;
        let headers = String::from_utf8_lossy(&response[..split]);
        let mut lines = headers.lines();
        let status = lines
            .next()
            .and_then(|s| s.split_whitespace().nth(1))
            .unwrap_or("")
            .parse::<u16>()
            .context("invalid HTTP status")?;
        if (300..400).contains(&status) {
            let location = lines
                .find_map(|line| {
                    line.split_once(':')
                        .filter(|(k, _)| k.eq_ignore_ascii_case("location"))
                        .map(|(_, v)| v.trim())
                })
                .context("redirect without Location")?;
            url = url.join(location).context("invalid redirect URL")?;
            validate_local_url(&url)?;
            continue;
        }
        if status != 200 {
            bail!("local server returned HTTP {status}")
        }
        let body = &response[split + 4..];
        if body.len() > max_bytes {
            bail!("response exceeds --max-bytes")
        }
        return render_web(&url, &String::from_utf8_lossy(body));
    }
    bail!("too many redirects")
}

fn render_web(url: &Url, source: &str) -> Result<WebPage> {
    let document = Html::parse_document(source);
    let root_selector = Selector::parse("main, article, body").unwrap();
    let root = document
        .select(&root_selector)
        .next()
        .context("page has no readable body")?;
    let block_selector =
        Selector::parse("h1, h2, h3, h4, h5, h6, p, li, blockquote, pre, table").unwrap();
    let mut text = String::new();
    for block in root.select(&block_selector) {
        let name = block.value().name();
        let value = sanitize(&visible_html_text(block))
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        if value.is_empty() {
            continue;
        }
        match name {
            "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => text.push_str(&format!("\n{value}\n")),
            "li" => text.push_str(&format!("- {value}\n")),
            "blockquote" => text.push_str(&format!("> {value}\n")),
            "pre" => text.push_str(&format!("\n{value}\n")),
            _ => text.push_str(&format!("{value}\n\n")),
        }
    }
    if text.trim().is_empty() {
        text = sanitize(&visible_html_text(root));
    }
    let link_selector = Selector::parse("a[href]").unwrap();
    let mut links = Vec::new();
    let mut visible_links = Vec::new();
    for anchor in root.select(&link_selector) {
        if let Some(href) = anchor.value().attr("href") {
            if let Ok(link) = url.join(href) {
                let label = sanitize(&visible_html_text(anchor));
                if validate_local_url(&link).is_ok() {
                    links.push(link.clone());
                    visible_links.push(format!("  [{}] {} <{}>", links.len(), label, link));
                } else {
                    // Remote links are visible reading material, never navigation targets.
                    visible_links.push(format!("  {} <{}> (not navigable)", label, link));
                }
            }
        }
    }
    if !visible_links.is_empty() {
        text.push_str("\nLinks:\n");
        for link in visible_links {
            text.push_str(&link);
            text.push('\n');
        }
    }
    Ok(WebPage {
        url: url.clone(),
        text,
        links,
    })
}

fn visible_html_text(element: ElementRef<'_>) -> String {
    let mut text = String::new();
    for child in element.children() {
        match child.value() {
            Node::Text(value) => text.push_str(value),
            Node::Element(_) => {
                if let Some(child) = ElementRef::wrap(child)
                    && !is_ignored_html_element(child.value().name())
                {
                    text.push_str(&visible_html_text(child));
                }
            }
            _ => {}
        }
    }
    text
}

fn is_ignored_html_element(name: &str) -> bool {
    matches!(
        name,
        "script"
            | "style"
            | "form"
            | "input"
            | "select"
            | "textarea"
            | "button"
            | "img"
            | "picture"
            | "svg"
            | "canvas"
            | "iframe"
            | "noscript"
            | "template"
    )
}

fn run_web(cli: &Cli, stdout_is_tty: bool) -> i32 {
    let start = match Url::parse(&cli.files[0]) {
        Ok(url) => match validate_local_url(&url) {
            Ok(()) => url,
            Err(error) => {
                eprintln!("sl: {error}");
                return 1;
            }
        },
        Err(error) => {
            eprintln!("sl: {error}");
            return 1;
        }
    };
    if !stdout_is_tty || cli.no_pager || cli.plain {
        match fetch_web(&start, cli.max_bytes) {
            Ok(page) => {
                return write_stdout(&page.text).map_or_else(
                    |e| {
                        eprintln!("sl: write error: {e}");
                        1
                    },
                    |_| 0,
                );
            }
            Err(e) => {
                eprintln!("sl: {e:#}");
                return 1;
            }
        }
    }
    match web_ui(start, cli.max_bytes) {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("sl: web reader: {e:#}");
            1
        }
    }
}

struct TerminalGuard;
impl TerminalGuard {
    fn enter() -> Result<Self> {
        terminal::enable_raw_mode()?;
        execute!(io::stdout(), terminal::EnterAlternateScreen, cursor::Hide)?;
        Ok(Self)
    }
}
impl Drop for TerminalGuard {
    fn drop(&mut self) {
        let _ = execute!(io::stdout(), cursor::Show, terminal::LeaveAlternateScreen);
        let _ = terminal::disable_raw_mode();
    }
}

fn web_ui(start: Url, max_bytes: usize) -> Result<()> {
    let _guard = TerminalGuard::enter()?;
    let mut history = vec![fetch_web(&start, max_bytes)?];
    let mut position = 0usize;
    let mut offset = 0usize;
    let mut link_number = String::new();
    loop {
        let (_, rows) = terminal::size()?;
        let page = &history[position];
        execute!(
            io::stdout(),
            cursor::MoveTo(0, 0),
            terminal::Clear(ClearType::All)
        )?;
        println!("sl local web: {}  (q help: ?) {}", page.url, link_number);
        let lines: Vec<_> = page.text.lines().collect();
        let height = rows.saturating_sub(2) as usize;
        for line in lines.iter().skip(offset).take(height) {
            println!("{}", truncate_display(line, terminal::size()?.0 as usize));
        }
        io::stdout().flush()?;
        if let Event::Key(key) = event::read()? {
            match key.code {
                KeyCode::Char('q') => break,
                KeyCode::Down | KeyCode::Char('j') => {
                    offset = (offset + 1).min(lines.len().saturating_sub(1))
                }
                KeyCode::Up | KeyCode::Char('k') => offset = offset.saturating_sub(1),
                KeyCode::PageDown => offset = (offset + height).min(lines.len().saturating_sub(1)),
                KeyCode::PageUp => offset = offset.saturating_sub(height),
                KeyCode::Char('b') | KeyCode::Left => {
                    if position > 0 {
                        position -= 1;
                        offset = 0
                    }
                }
                KeyCode::Char('f') | KeyCode::Right => {
                    if position + 1 < history.len() {
                        position += 1;
                        offset = 0
                    }
                }
                KeyCode::Char('r') => {
                    history[position] = fetch_web(&history[position].url, max_bytes)?;
                    offset = 0
                }
                KeyCode::Char('?') => {
                    execute!(
                        io::stdout(),
                        terminal::Clear(ClearType::All),
                        cursor::MoveTo(0, 0)
                    )?;
                    println!(
                        "j/k or arrows scroll; / search; type a link number then Enter; b/f back/forward; r reload; q quit\nPress any key."
                    );
                    let _ = event::read()?;
                }
                KeyCode::Char('/') => {
                    if let Some(query) = web_prompt("Search: ")? {
                        if let Some(found) = lines.iter().position(|line| {
                            line.to_ascii_lowercase()
                                .contains(&query.to_ascii_lowercase())
                        }) {
                            offset = found;
                        }
                    }
                }
                KeyCode::Char(digit) if digit.is_ascii_digit() => link_number.push(digit),
                KeyCode::Backspace => {
                    link_number.pop();
                }
                KeyCode::Enter => {
                    if let Ok(number) = link_number.parse::<usize>() {
                        if let Some(link) = page.links.get(number.saturating_sub(1)) {
                            let next = fetch_web(link, max_bytes)?;
                            history.truncate(position + 1);
                            history.push(next);
                            position += 1;
                            offset = 0;
                        }
                    }
                    link_number.clear();
                }
                _ => {}
            }
        }
    }
    Ok(())
}

fn web_prompt(label: &str) -> Result<Option<String>> {
    let (_, rows) = terminal::size()?;
    execute!(
        io::stdout(),
        cursor::MoveTo(0, rows.saturating_sub(1)),
        terminal::Clear(ClearType::CurrentLine)
    )?;
    print!("{label}");
    io::stdout().flush()?;
    let mut value = String::new();
    loop {
        if let Event::Key(key) = event::read()? {
            match key.code {
                KeyCode::Enter => return Ok((!value.is_empty()).then_some(value)),
                KeyCode::Esc => return Ok(None),
                KeyCode::Backspace => {
                    value.pop();
                }
                KeyCode::Char(c) => value.push(c),
                _ => {}
            }
            execute!(
                io::stdout(),
                cursor::MoveTo(0, rows.saturating_sub(1)),
                terminal::Clear(ClearType::CurrentLine)
            )?;
            print!("{label}{value}");
            io::stdout().flush()?;
        }
    }
}

fn page(output: &str) -> Result<()> {
    let pager = minus::Pager::new();
    pager
        .set_run_no_overflow(true)
        .context("could not configure pager")?;
    pager
        .push_str(output)
        .context("could not prepare pager output")?;
    minus::page_all(pager).context("could not start pager")?;
    Ok(())
}

fn write_stdout(output: &str) -> io::Result<()> {
    let mut stdout = io::stdout().lock();
    stdout.write_all(output.as_bytes())?;
    stdout.flush()
}

fn read_and_render(
    source: &str,
    forced_kind: Option<DocumentKind>,
    max_bytes: usize,
    options: RenderOptions,
) -> Result<(String, Option<String>)> {
    let (bytes, truncated) = read_source(source, max_bytes)?;
    let kind = forced_kind
        .unwrap_or_else(|| DocumentKind::detect((source != "-").then_some(source), &bytes));
    let mut warning = truncated.then(|| format!("input was truncated at {max_bytes} bytes"));
    let rendered = match render(kind, &bytes, options, (source != "-").then_some(source)) {
        Ok(rendered) => rendered,
        Err(error) => {
            warning = Some(format!("{}; rendered safely as text", error));
            render_text(&String::from_utf8_lossy(&bytes), options)
        }
    };
    Ok((rendered, warning))
}

fn read_source(source: &str, max_bytes: usize) -> Result<(Vec<u8>, bool)> {
    let mut reader: Box<dyn Read> = if source == "-" {
        Box::new(io::stdin().lock())
    } else {
        Box::new(fs::File::open(source).with_context(|| "could not open input")?)
    };
    let mut bytes = Vec::with_capacity(max_bytes.min(64 * 1024));
    let mut limited = reader.by_ref().take(max_bytes as u64 + 1);
    limited
        .read_to_end(&mut bytes)
        .context("could not read input")?;
    let truncated = bytes.len() > max_bytes;
    if truncated {
        bytes.truncate(max_bytes);
    }
    Ok((bytes, truncated))
}

fn render(
    kind: DocumentKind,
    bytes: &[u8],
    options: RenderOptions,
    source: Option<&str>,
) -> Result<String> {
    let rendered = match kind {
        DocumentKind::Text => Ok(render_text(&String::from_utf8_lossy(bytes), options)),
        DocumentKind::Markdown => Ok(render_markdown(&String::from_utf8_lossy(bytes), options)),
        DocumentKind::Json => render_json(bytes, options),
        DocumentKind::Yaml => render_yaml(bytes, options),
        DocumentKind::Toml => render_toml(bytes, options),
        DocumentKind::Csv => render_delimited(bytes, b',', options),
        DocumentKind::Tsv => render_delimited(bytes, b'\t', options),
        DocumentKind::Code => Ok(render_code(
            &String::from_utf8_lossy(bytes),
            source.and_then(SourceLanguage::from_name),
            options,
        )),
        DocumentKind::Binary => Ok(render_binary(bytes, options)),
    }?;
    Ok(apply_theme(rendered, options.theme))
}

fn render_json(bytes: &[u8], options: RenderOptions) -> Result<String> {
    let value: serde_json::Value = serde_json::from_slice(bytes).context("invalid JSON")?;
    let pretty = serde_json::to_string_pretty(&value)?;
    Ok(render_structured(&pretty, options))
}

fn render_yaml(bytes: &[u8], options: RenderOptions) -> Result<String> {
    let text = std::str::from_utf8(bytes).context("YAML is not UTF-8")?;
    let _: serde_yaml_ng::Value = serde_yaml_ng::from_str(text).context("invalid YAML")?;
    Ok(render_structured(text, options))
}

fn render_toml(bytes: &[u8], options: RenderOptions) -> Result<String> {
    let text = std::str::from_utf8(bytes).context("TOML is not UTF-8")?;
    let _: toml::Value = toml::from_str(text).context("invalid TOML")?;
    Ok(render_structured(text, options))
}

fn render_structured(text: &str, options: RenderOptions) -> String {
    text.lines()
        .map(|line| {
            let safe = sanitize(line);
            let styled = if safe.trim_start().starts_with(['{', '}', '[', ']']) {
                style(&safe, "36", options.color)
            } else if safe.contains(':') || safe.contains('=') {
                style(&safe, "33", options.color)
            } else {
                safe
            };
            format!("{}\n", styled)
        })
        .collect()
}

fn render_code(text: &str, language: Option<SourceLanguage>, options: RenderOptions) -> String {
    let language = language.unwrap_or(SourceLanguage::Generic);
    let line_count = text.lines().count().max(1);
    let digits = line_count.to_string().len();
    text.lines()
        .enumerate()
        .map(|(index, line)| {
            let line = truncate_display(&sanitize(line), options.width);
            let line = highlight_code_line(&line, language, options.color);
            if options.line_numbers {
                format!(
                    "{} {}\n",
                    style(&format!("{:>digits$}", index + 1), "2;90", options.color),
                    line
                )
            } else {
                format!("{line}\n")
            }
        })
        .collect()
}

fn highlight_code_line(line: &str, language: SourceLanguage, color: bool) -> String {
    let mut output = String::with_capacity(line.len());
    let mut position = 0;
    while position < line.len() {
        let remaining = &line[position..];
        if is_comment_start(remaining, language) {
            output.push_str(&style(remaining, "2;90", color));
            break;
        }
        let Some(character) = remaining.chars().next() else {
            break;
        };
        if matches!(character, '\'' | '"' | '`') {
            let end = string_end(remaining, character);
            output.push_str(&style(&remaining[..end], "32", color));
            position += end;
        } else if character.is_ascii_digit() {
            let end = remaining
                .char_indices()
                .take_while(|(_, value)| {
                    value.is_ascii_alphanumeric() || matches!(value, '.' | '_')
                })
                .last()
                .map_or(character.len_utf8(), |(index, value)| {
                    index + value.len_utf8()
                });
            output.push_str(&style(&remaining[..end], "36", color));
            position += end;
        } else if character.is_ascii_alphabetic() || character == '_' {
            let end = remaining
                .char_indices()
                .take_while(|(_, value)| value.is_ascii_alphanumeric() || *value == '_')
                .last()
                .map_or(character.len_utf8(), |(index, value)| {
                    index + value.len_utf8()
                });
            let word = &remaining[..end];
            output.push_str(&style(word, "35", color && is_keyword(word, language)));
            position += end;
        } else {
            output.push(character);
            position += character.len_utf8();
        }
    }
    output
}

fn is_comment_start(remaining: &str, language: SourceLanguage) -> bool {
    remaining.starts_with("//")
        || remaining.starts_with("/*")
        || matches!(language, SourceLanguage::Python | SourceLanguage::Shell)
            && remaining.starts_with('#')
        || matches!(language, SourceLanguage::Generic) && remaining.starts_with(['#', ';'])
}

fn string_end(input: &str, quote: char) -> usize {
    let mut escaped = false;
    for (index, character) in input.char_indices().skip(1) {
        if character == quote && !escaped {
            return index + character.len_utf8();
        }
        escaped = character == '\\' && !escaped;
        if character != '\\' {
            escaped = false;
        }
    }
    input.len()
}

fn is_keyword(word: &str, language: SourceLanguage) -> bool {
    let common = matches!(
        word,
        "if" | "else" | "for" | "while" | "return" | "true" | "false" | "null"
    );
    common
        || match language {
            SourceLanguage::Rust => matches!(
                word,
                "as" | "async"
                    | "await"
                    | "const"
                    | "enum"
                    | "fn"
                    | "impl"
                    | "let"
                    | "match"
                    | "mod"
                    | "move"
                    | "mut"
                    | "pub"
                    | "struct"
                    | "trait"
                    | "use"
                    | "where"
            ),
            SourceLanguage::Python => matches!(
                word,
                "and"
                    | "as"
                    | "class"
                    | "def"
                    | "elif"
                    | "from"
                    | "import"
                    | "in"
                    | "is"
                    | "lambda"
                    | "None"
                    | "not"
                    | "or"
                    | "pass"
                    | "True"
                    | "False"
                    | "with"
                    | "yield"
            ),
            SourceLanguage::JavaScript => matches!(
                word,
                "async"
                    | "await"
                    | "class"
                    | "const"
                    | "export"
                    | "function"
                    | "import"
                    | "interface"
                    | "let"
                    | "new"
                    | "undefined"
                    | "var"
            ),
            SourceLanguage::Shell => matches!(
                word,
                "case" | "do" | "done" | "echo" | "esac" | "fi" | "function" | "in" | "then"
            ),
            SourceLanguage::Go => matches!(
                word,
                "chan"
                    | "defer"
                    | "func"
                    | "go"
                    | "map"
                    | "package"
                    | "range"
                    | "select"
                    | "type"
                    | "var"
            ),
            SourceLanguage::Generic => matches!(
                word,
                "class" | "define" | "function" | "include" | "package" | "section"
            ),
        }
}

fn render_text(text: &str, options: RenderOptions) -> String {
    let line_count = text.lines().count().max(1);
    let digits = line_count.to_string().len();
    text.lines()
        .enumerate()
        .map(|(index, line)| {
            let line = truncate_display(&sanitize(line), options.width);
            if options.line_numbers {
                format!(
                    "{} {}\n",
                    style(&format!("{:>digits$}", index + 1), "2;90", options.color),
                    line
                )
            } else {
                format!("{line}\n")
            }
        })
        .collect()
}

fn render_markdown(text: &str, options: RenderOptions) -> String {
    let lines = text.lines().map(sanitize).collect::<Vec<_>>();
    let mut output = String::new();
    let mut index = 0;
    while index < lines.len() {
        let line = &lines[index];
        let trimmed = line.trim_start();
        if is_fence(trimmed) {
            // Code (including Mermaid) is deliberately displayed as source, not interpreted.
            output.push_str(&style(line, "2;35", options.color));
            output.push('\n');
            index += 1;
            while index < lines.len() {
                output.push_str(&style(&lines[index], "2", options.color));
                output.push('\n');
                if is_fence(lines[index].trim_start()) {
                    index += 1;
                    break;
                }
                index += 1;
            }
        } else if index + 1 < lines.len()
            && line.contains('|')
            && is_table_divider(&lines[index + 1])
        {
            let mut rows = vec![split_table_row(line)];
            let alignments = table_alignments(&lines[index + 1]);
            index += 2; // The divider is formatting, not document content.
            while index < lines.len()
                && lines[index].contains('|')
                && !lines[index].trim().is_empty()
            {
                rows.push(split_table_row(&lines[index]));
                index += 1;
            }
            output.push_str(&render_markdown_table(&rows, &alignments, options));
        } else if line.trim().is_empty() {
            output.push('\n');
            index += 1;
        } else if let Some((level, title)) = heading(trimmed) {
            for wrapped in wrap_display(&inline_markdown(title), options.width) {
                output.push_str(&style(
                    &wrapped,
                    if level == 1 { "1;36" } else { "1;34" },
                    options.color,
                ));
                output.push('\n');
            }
            index += 1;
        } else if let Some((prefix, body, quote)) = markdown_prefix(trimmed) {
            let mut paragraph = vec![body.to_owned()];
            index += 1;
            while index < lines.len() {
                let candidate = lines[index].trim_start();
                if candidate.is_empty()
                    || is_fence(candidate)
                    || heading(candidate).is_some()
                    || markdown_prefix(candidate).is_some()
                    || (candidate.contains('|')
                        && index + 1 < lines.len()
                        && is_table_divider(&lines[index + 1]))
                {
                    break;
                }
                paragraph.push(candidate.to_owned());
                index += 1;
            }
            let continuation = " ".repeat(display_width(prefix));
            for (line_number, wrapped) in wrap_display(
                &inline_markdown(&paragraph.join(" ")),
                options.width.saturating_sub(display_width(prefix)),
            )
            .iter()
            .enumerate()
            {
                let marker = if line_number == 0 || quote {
                    prefix
                } else {
                    &continuation
                };
                output.push_str(&style(
                    &format!("{marker}{wrapped}"),
                    if quote { "2;33" } else { "32" },
                    options.color,
                ));
                output.push('\n');
            }
        } else {
            let mut paragraph = vec![trimmed.to_owned()];
            index += 1;
            while index < lines.len() {
                let candidate = lines[index].trim_start();
                if candidate.is_empty()
                    || is_fence(candidate)
                    || heading(candidate).is_some()
                    || markdown_prefix(candidate).is_some()
                    || (candidate.contains('|')
                        && index + 1 < lines.len()
                        && is_table_divider(&lines[index + 1]))
                {
                    break;
                }
                paragraph.push(candidate.to_owned());
                index += 1;
            }
            for wrapped in wrap_display(&inline_markdown(&paragraph.join(" ")), options.width) {
                output.push_str(&wrapped);
                output.push('\n');
            }
        }
    }
    output
}

fn is_fence(line: &str) -> bool {
    line.starts_with("```") || line.starts_with("~~~")
}

fn heading(line: &str) -> Option<(usize, &str)> {
    let count = line
        .chars()
        .take_while(|character| *character == '#')
        .count();
    (count > 0 && count <= 6 && line.as_bytes().get(count) == Some(&b' '))
        .then(|| (count, line[count..].trim()))
}

fn markdown_prefix(line: &str) -> Option<(&str, &str, bool)> {
    if let Some(body) = line.strip_prefix("> ") {
        return Some(("> ", body, true));
    }
    for marker in ["- ", "* ", "+ "] {
        if let Some(body) = line.strip_prefix(marker) {
            return Some((marker, body, false));
        }
    }
    let digits = line.bytes().take_while(u8::is_ascii_digit).count();
    if digits > 0 && line[digits..].starts_with(". ") {
        return Some((&line[..digits + 2], &line[digits + 2..], false));
    }
    None
}

fn inline_markdown(input: &str) -> String {
    let mut output = String::new();
    let mut rest = input;
    while let Some(open) = rest.find('[') {
        output.push_str(&rest[..open]);
        let after_open = &rest[open + 1..];
        let Some(close) = after_open.find("](") else {
            output.push('[');
            rest = after_open;
            continue;
        };
        let label = &after_open[..close];
        let after_label = &after_open[close + 2..];
        let Some(end) = after_label.find(')') else {
            output.push('[');
            rest = after_open;
            continue;
        };
        output.push_str(label);
        output.push_str(" <");
        output.push_str(&after_label[..end]);
        output.push('>');
        rest = &after_label[end + 1..];
    }
    output.push_str(rest);
    output
}

fn display_width(input: &str) -> usize {
    unicode_width::UnicodeWidthStr::width(input)
}

fn wrap_display(input: &str, width: usize) -> Vec<String> {
    let width = width.max(1);
    let mut lines = Vec::new();
    let mut current = String::new();
    let mut used = 0;
    for word in input.split_whitespace() {
        let word_width = display_width(word);
        let separator = usize::from(!current.is_empty());
        if used + separator + word_width > width && !current.is_empty() {
            lines.push(current);
            current = String::new();
            used = 0;
        }
        if !current.is_empty() {
            current.push(' ');
            used += 1;
        }
        current.push_str(word);
        used += word_width;
    }
    if !current.is_empty() {
        lines.push(current);
    }
    lines
}

fn split_table_row(row: &str) -> Vec<String> {
    let row = row.trim();
    let row = row.strip_prefix('|').unwrap_or(row);
    let row = row.strip_suffix('|').unwrap_or(row);
    let mut cells = Vec::new();
    let mut cell = String::new();
    let mut escaped = false;
    for character in row.chars() {
        if escaped {
            cell.push(character);
            escaped = false;
        } else if character == '\\' {
            escaped = true;
        } else if character == '|' {
            cells.push(inline_markdown(cell.trim()));
            cell.clear();
        } else {
            cell.push(character);
        }
    }
    if escaped {
        cell.push('\\');
    }
    cells.push(inline_markdown(cell.trim()));
    cells
}

fn is_table_divider(row: &str) -> bool {
    let cells = split_table_row(row);
    !cells.is_empty()
        && cells.iter().all(|cell| {
            let core = cell.trim().trim_matches(':');
            core.len() >= 3 && core.bytes().all(|byte| byte == b'-')
        })
}

#[derive(Clone, Copy)]
enum TableAlignment {
    Left,
    Center,
    Right,
}

fn table_alignments(row: &str) -> Vec<TableAlignment> {
    split_table_row(row)
        .iter()
        .map(
            |cell| match (cell.trim().starts_with(':'), cell.trim().ends_with(':')) {
                (true, true) => TableAlignment::Center,
                (_, true) => TableAlignment::Right,
                _ => TableAlignment::Left,
            },
        )
        .collect()
}

fn render_markdown_table(
    rows: &[Vec<String>],
    alignments: &[TableAlignment],
    options: RenderOptions,
) -> String {
    let columns = rows.iter().map(Vec::len).max().unwrap_or(0);
    if columns == 0 {
        return String::new();
    }
    let available = options.width.saturating_sub(columns * 3 + 1).max(columns);
    let desired = (0..columns)
        .map(|column| {
            rows.iter()
                .filter_map(|row| row.get(column))
                .map(|cell| display_width(cell))
                .max()
                .unwrap_or(1)
        })
        .collect::<Vec<_>>();
    let mut widths = vec![1; columns];
    let mut remaining = available.saturating_sub(columns);
    while remaining > 0 {
        let mut changed = false;
        for column in 0..columns {
            if remaining > 0 && widths[column] < desired[column] {
                widths[column] += 1;
                remaining -= 1;
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }
    let mut output = String::new();
    for (row_index, row) in rows.iter().enumerate() {
        let cells = (0..columns)
            .map(|column| {
                wrap_display(
                    row.get(column).map(String::as_str).unwrap_or(""),
                    widths[column],
                )
            })
            .collect::<Vec<_>>();
        let height = cells.iter().map(Vec::len).max().unwrap_or(1);
        for line in 0..height {
            let rendered = (0..columns)
                .map(|column| {
                    pad_table_cell(
                        cells[column].get(line).map(String::as_str).unwrap_or(""),
                        widths[column],
                        *alignments.get(column).unwrap_or(&TableAlignment::Left),
                    )
                })
                .collect::<Vec<_>>()
                .join(" | ");
            output.push_str(&style(
                &format!("| {rendered} |"),
                if row_index == 0 { "1;36" } else { "" },
                options.color,
            ));
            output.push('\n');
        }
    }
    output
}

fn render_delimited(bytes: &[u8], delimiter: u8, options: RenderOptions) -> Result<String> {
    let mut reader = csv::ReaderBuilder::new()
        .has_headers(false)
        .delimiter(delimiter)
        .from_reader(bytes);
    let mut rows = Vec::new();
    for record in reader.records().take(100) {
        rows.push(record?.iter().map(sanitize).collect::<Vec<_>>());
    }
    if rows.is_empty() {
        return Ok(String::new());
    }
    let columns = rows.iter().map(Vec::len).max().unwrap_or(0).min(12);
    let mut widths = vec![3; columns];
    for row in &rows {
        for (index, value) in row.iter().take(columns).enumerate() {
            widths[index] =
                widths[index].max(unicode_width::UnicodeWidthStr::width(value.as_str()).min(30));
        }
    }
    let mut output = String::new();
    for (row_index, row) in rows.iter().enumerate() {
        let cells = (0..columns)
            .map(|index| {
                pad_display(
                    row.get(index).map(String::as_str).unwrap_or(""),
                    widths[index],
                )
            })
            .collect::<Vec<_>>();
        let line = format!("| {} |", cells.join(" | "));
        output.push_str(&style(
            &truncate_display(&line, options.width),
            if row_index == 0 { "1;36" } else { "" },
            options.color,
        ));
        output.push('\n');
    }
    Ok(output)
}

fn pad_table_cell(input: &str, width: usize, alignment: TableAlignment) -> String {
    let padding = width.saturating_sub(display_width(input));
    match alignment {
        TableAlignment::Left => format!("{input}{}", " ".repeat(padding)),
        TableAlignment::Right => format!("{}{input}", " ".repeat(padding)),
        TableAlignment::Center => {
            let left = padding / 2;
            format!(
                "{}{}{}",
                " ".repeat(left),
                input,
                " ".repeat(padding - left)
            )
        }
    }
}

fn render_binary(bytes: &[u8], options: RenderOptions) -> String {
    let mut output = String::new();
    for (offset, chunk) in bytes.chunks(16).take(256).enumerate() {
        let hex = chunk
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<Vec<_>>()
            .join(" ");
        let ascii: String = chunk
            .iter()
            .map(|byte| {
                if byte.is_ascii_graphic() {
                    *byte as char
                } else {
                    '.'
                }
            })
            .collect();
        output.push_str(&format!(
            "{}  {:<47}  {}\n",
            style(&format!("{:08x}", offset * 16), "2;90", options.color),
            hex,
            ascii
        ));
    }
    output
}

fn sanitize(input: &str) -> String {
    input
        .chars()
        .map(|character| match character {
            ESC => '␛',
            character if character.is_control() && character != '\t' => '�',
            character => character,
        })
        .collect()
}

fn truncate_display(input: &str, width: usize) -> String {
    let mut result = String::new();
    let mut used = 0;
    for character in input.chars() {
        // ANSI escape sequences generated by us are left intact; their display width is zero.
        if character == ESC {
            result.push(character);
            continue;
        }
        let character_width = unicode_width::UnicodeWidthChar::width(character).unwrap_or(0);
        if used + character_width > width.saturating_sub(1) {
            result.push('…');
            break;
        }
        used += character_width;
        result.push(character);
    }
    result
}

fn pad_display(input: &str, width: usize) -> String {
    let clipped = truncate_display(input, width + 1);
    let padding = width.saturating_sub(unicode_width::UnicodeWidthStr::width(clipped.as_str()));
    format!("{clipped}{}", " ".repeat(padding))
}

fn theme_code(code: &str, theme: Theme) -> &str {
    match (theme, code) {
        // Brighter foregrounds keep highlighted source readable on dark terminals.
        (Theme::Dark, "1;36") => "1;96",
        (Theme::Dark, "1;34") => "1;94",
        (Theme::Dark, "36") => "96",
        (Theme::Dark, "33") => "93",
        (Theme::Dark, "32") => "92",
        (Theme::Dark, "35") => "95",
        _ => code,
    }
}

fn apply_theme(rendered: String, theme: Theme) -> String {
    if theme != Theme::Dark {
        return rendered;
    }
    [
        ("\x1b[1;36m", "\x1b[1;96m"),
        ("\x1b[1;34m", "\x1b[1;94m"),
        ("\x1b[36m", "\x1b[96m"),
        ("\x1b[33m", "\x1b[93m"),
        ("\x1b[32m", "\x1b[92m"),
        ("\x1b[35m", "\x1b[95m"),
    ]
    .into_iter()
    .fold(rendered, |output, (from, to)| output.replace(from, to))
}

fn style(input: &str, code: &str, enabled: bool) -> String {
    if enabled && !code.is_empty() {
        // `input` has already passed through sanitize at every rendering boundary.
        // These are the only control sequences this program generates.
        format!("\x1b[{code}m{input}\x1b[0m")
    } else {
        input.to_owned()
    }
}

fn looks_like_markdown(bytes: &[u8]) -> bool {
    let Ok(text) = std::str::from_utf8(bytes) else {
        return false;
    };
    let lines = text.lines().take(80).collect::<Vec<_>>();
    let list_or_quote_count = lines
        .iter()
        .filter(|line| markdown_prefix(line.trim_start()).is_some())
        .count();
    lines.iter().enumerate().any(|(index, line)| {
        let trimmed = line.trim_start();
        heading(trimmed).is_some()
            || is_fence(trimmed)
            || (line.contains('[') && line.contains("]("))
            || (line.contains('|')
                && lines
                    .get(index + 1)
                    .is_some_and(|next| is_table_divider(next)))
    }) || list_or_quote_count >= 2
}

fn looks_like_json(bytes: &[u8]) -> bool {
    let text = String::from_utf8_lossy(bytes);
    let trimmed = text.trim_start();
    (trimmed.starts_with('{') || trimmed.starts_with('['))
        && serde_json::from_str::<serde_json::Value>(&text).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extensions_take_priority() {
        assert_eq!(
            DocumentKind::detect(Some("report.JSON"), b"not JSON"),
            DocumentKind::Json
        );
        assert_eq!(
            DocumentKind::detect(Some("README.md"), b"{}"),
            DocumentKind::Markdown
        );
        assert_eq!(
            DocumentKind::detect(Some("unknown"), b"{}"),
            DocumentKind::Json
        );
    }

    #[test]
    fn source_extensions_select_code_without_overriding_structured_formats() {
        for name in [
            "main.rs",
            "tool.py",
            "app.ts",
            "script.sh",
            "server.go",
            "settings.ini",
            "Dockerfile",
            "CMakeLists.txt",
            ".editorconfig",
        ] {
            assert_eq!(
                DocumentKind::detect(Some(name), b"not structured"),
                DocumentKind::Code
            );
        }
        assert_eq!(
            DocumentKind::detect(Some("data.json"), b"let x = 1"),
            DocumentKind::Json
        );
        assert_eq!(
            DocumentKind::detect(Some("config.yaml"), b"let x = 1"),
            DocumentKind::Yaml
        );
        assert_eq!(
            DocumentKind::detect(Some("Cargo.toml"), b"let x = 1"),
            DocumentKind::Toml
        );
        assert_eq!(
            DocumentKind::detect(Some("data.csv"), b"let,x"),
            DocumentKind::Csv
        );
        assert_eq!(
            DocumentKind::detect(Some("notes.md"), b"let x = 1"),
            DocumentKind::Markdown
        );
    }

    #[test]
    fn terminal_controls_are_visible() {
        assert_eq!(sanitize("hello\x1b[2J"), "hello␛[2J");
    }

    #[test]
    fn code_highlighting_sanitizes_input_ansi_sequences() {
        let rendered = render_code(
            "let value = \"\x1b[2J\"; // \x1b[31m",
            Some(SourceLanguage::Rust),
            RenderOptions {
                color: true,
                theme: Theme::Default,
                width: 80,
                line_numbers: false,
            },
        );
        assert!(rendered.contains("␛[2J"));
        assert!(rendered.contains("␛[31m"));
        assert!(!rendered.contains("\x1b[2J"));
        assert!(!rendered.contains("\x1b[31m"));
    }

    #[test]
    fn plain_code_rendering_has_no_ansi_sequences() {
        let rendered = render_code(
            "fn main() { println!(\"hello\"); }",
            Some(SourceLanguage::Rust),
            RenderOptions {
                color: false,
                theme: Theme::Default,
                width: 80,
                line_numbers: false,
            },
        );
        assert_eq!(rendered, "fn main() { println!(\"hello\"); }\n");
        assert!(!rendered.contains(ESC));
    }

    #[test]
    fn json_is_pretty_printed() {
        let rendered = render_json(
            br#"{"a":[1,2]}"#,
            RenderOptions {
                color: false,
                theme: Theme::Default,
                width: 80,
                line_numbers: false,
            },
        )
        .unwrap();
        assert!(rendered.contains("\"a\": ["));
    }

    #[test]
    fn csv_is_tabular() {
        let rendered = render_delimited(
            b"name,age\nAda,37\n",
            b',',
            RenderOptions {
                color: false,
                theme: Theme::Default,
                width: 80,
                line_numbers: false,
            },
        )
        .unwrap();
        assert!(rendered.contains("| name | age |"));
    }

    #[test]
    fn yaml_and_toml_are_validated() {
        let options = RenderOptions {
            color: false,
            theme: Theme::Default,
            width: 80,
            line_numbers: false,
        };
        assert!(render_yaml(b"title: smart-less\n", options).is_ok());
        assert!(render_toml(b"title = 'smart-less'\n", options).is_ok());
        assert!(render_yaml(b"title: [\n", options).is_err());
        assert!(render_toml(b"title = [\n", options).is_err());
    }

    #[test]
    fn markdown_keeps_mermaid_as_safe_source() {
        let rendered = render_markdown(
            "# Diagram\n```mermaid\ngraph TD\n  A-->B\n```",
            RenderOptions {
                color: false,
                theme: Theme::Default,
                width: 20,
                line_numbers: false,
            },
        );
        assert!(rendered.contains("graph TD"));
        assert!(rendered.contains("  A-->B"));
    }

    #[test]
    fn markdown_is_sniffed_from_stdin_content() {
        assert_eq!(
            DocumentKind::detect(None, b"# Notes\n\n- first\n- second\n"),
            DocumentKind::Markdown
        );
        assert_eq!(
            DocumentKind::detect(None, b"ordinary text\n"),
            DocumentKind::Text
        );
    }

    #[test]
    fn markdown_reflows_prose_lists_quotes_and_links_without_clipping() {
        let rendered = render_markdown(
            "A [useful link](https://example.test/docs) has enough words to wrap safely.\n\n- a list item with enough words to wrap safely\n> a quoted sentence with enough words to wrap safely",
            RenderOptions {
                color: false,
                theme: Theme::Default,
                width: 24,
                line_numbers: false,
            },
        );
        assert!(rendered.contains("useful link"));
        assert!(rendered.contains("<https://example.test/docs>"));
        assert!(rendered.contains("- a list item"));
        assert!(rendered.contains("> a quoted sentence"));
        assert!(!rendered.contains('…'));
    }

    #[test]
    fn local_web_urls_and_html_are_constrained() -> Result<()> {
        for value in [
            "http://localhost:3000/a",
            "http://127.1.2.3/a",
            "http://[::1]/a",
        ] {
            assert!(validate_local_url(&Url::parse(value)?).is_ok());
        }
        for value in [
            "https://localhost/a",
            "http://192.168.1.2/a",
            "http://user@localhost/a",
        ] {
            assert!(validate_local_url(&Url::parse(value)?).is_err());
        }
        let page = render_web(
            &Url::parse("http://localhost:3000/")?,
            "<main><h1>Title</h1><p>Hello <b>reader</b><script>bad()</script>.</p><form>bad</form><a href='/next'>Next</a><a href='http://example.test/'>Remote</a></main>",
        )?;
        assert!(page.text.contains("Title"));
        assert!(page.text.contains("Hello reader"));
        assert!(!page.text.contains("bad"));
        assert_eq!(page.links, vec![Url::parse("http://localhost:3000/next")?]);
        Ok(())
    }

    #[test]
    fn markdown_tables_remove_divider_and_wrap_cells() {
        let rendered = render_markdown(
            "| Name | Description |\n| :--- | ---: |\n| Ada | A long description that wraps rather than being clipped |",
            RenderOptions {
                color: false,
                theme: Theme::Default,
                width: 30,
                line_numbers: false,
            },
        );
        assert!(rendered.contains("| Name"));
        assert!(rendered.contains("than being clipped"));
        assert!(!rendered.contains("---"));
        assert!(rendered.lines().all(|line| display_width(line) <= 30));
    }
}
